name: Build C++ CMake Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev libasound2-dev

      - name: Configure CMake (Linux/Windows)
        if: runner.os != 'macOS'
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DPRODUCTION_BUILD=ON
          -DGLFW_BUILD_EXAMPLES=OFF
          -DGLFW_BUILD_TESTS=OFF
          -DGLFW_BUILD_DOCS=OFF
          "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"

      - name: Configure CMake (macOS universal)
        if: runner.os == 'macOS'
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DPRODUCTION_BUILD=ON
          -DGLFW_BUILD_EXAMPLES=OFF
          -DGLFW_BUILD_TESTS=OFF
          -DGLFW_BUILD_DOCS=OFF
          -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
          -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0
          "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"

      - name: Build Project
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} -j 2

      # Single-config (Linux/Mac Make): build/mygame
      - name: Upload Artifacts (Linux/macOS)
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}-${{ matrix.build_type }}
          path: ${{ github.workspace }}/build/mygame
          if-no-files-found: error

      # Multi-config (Windows MSVC): build/Release/mygame.exe
      - name: Upload Artifacts (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}-${{ matrix.build_type }}
          path: |
            ${{ github.workspace }}/build/${{ matrix.build_type }}/mygame.exe
                shaders/
                resources/
          if-no-files-found: error